### ISSUE TITLE
Ambassador Swag Pack for 2022

### ISSUE THREAD

**Issue by caniszczyk** [cncf/ambassadors#104]
Let's organize a special swag bag for ambassadors and get it to them before kubecon.

**Comment by nate-double-u** [comment]
I once received a [Rickshaw bag](https://www.rickshawbags.com/) at a Twitter conference in SF (this must have been circa 2014-15) -- it had the fabric logo embroidered on it, and had a twitter pattern done up on the inside. I still use that bag. Nothing like a good bag for swag.

**Comment by ashutosh887** [comment]
Even I'll be glad to get a Swag pack @caniszczyk Sir

**Comment by amye** [comment]
We're reworking this program, closing in favor of next steps.
