### ISSUE TITLE
Broken Links on Readme

### ISSUE THREAD

**Issue by iamNoah1** [cncf/ambassadors#105]
On the Readme file in the Ambassador Benefits Section, the following links are broken: 

[Become a host](https://github.com/cncf/ambassadors/blob/master/Hosting-This-Week-in-Cloud-Native.md)
[This Week in Cloud Native](http://cloudnative.tv/)

**Comment by caniszczyk** [comment]
@iamNoah1 I believe those should be removed now since that program was put on hold, work with @jeefy

**Comment by jeefy** [comment]
Cleaned up, thanks @iamNoah1!
