### ISSUE TITLE
The floating go to top Button partially covers the submit an issue with this page.

### ISSUE THREAD

**Issue by parmishh** [cncf/ambassadors#113]
The floating go to top Button partially covers the submit an issue with this page. That makes it sometimes click on go to top rather than submit an issue with this page link.

https://github.com/cncf/ambassadors/assets/91942072/d96406f4-a2b6-47c4-96c5-c5bc15c412cb

I have made some changes now it doesn't overlap:

https://github.com/cncf/ambassadors/assets/91942072/20bf5283-cf97-42b2-98d8-b266f6d2e7cd

If this issue needs to be addressed please assign it to me.
@amye

**Comment by k8tgreenley** [comment]
Thank you @parmishh
