### ISSUE TITLE
Include BlueSky profile for Ambassadors

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/ambassadors#119]
BlueSky is becoming more and more used in the cloud native community. Many CNCF Ambassadors have joined already and can be found via a convenient [starter pack](https://bsky.app/starter-pack-short/JmYPdtB).

It would be great if Ambassadors could share their BlueSky profile also on the CNCF website.

**Comment by horovits** [comment]
this may require opening an issue on the website side

**Comment by cjyabraham** [comment]
This is now available. See [this example](https://github.com/cncf/people/commit/4f39899d2e6f37c1a11847d8eb217e68f1fcbc97) for how to add.

**Comment by ThomasVitale** [comment]
That's great, thank you!

**Comment by horovits** [comment]
thanks for the quick turnaround!
