### ISSUE TITLE
Google Map of Ambassadors + Location

### ISSUE THREAD

**Issue by caniszczyk** [cncf/ambassadors#12]

**Comment by onlydole** [comment]
@idvoretskyi - I'll send you a sheet I have that shows the current list of CNCF ambassadors and their location

**Comment by idvoretskyi** [comment]
@onlydole how you got the data? :)

**Comment by onlydole** [comment]
All via the publicly advertised profiles (ex. GitHub, LinkedIn, Twitter) on https://www.cncf.io/people/ambassadors/

**Comment by idvoretskyi** [comment]
@onlydole it contains a few errors, but it's a big work, thanks.

**Comment by onlydole** [comment]
Excellent! I can send over edit access if it’d be of help to correct any errors.

**Comment by luxas** [comment]
Any update on this?

**Comment by idvoretskyi** [comment]
@luxas WIP, the draft is ready; once it's finalized and approved - it will be publicly shared.

**Comment by idvoretskyi** [comment]
Fixed by https://github.com/cncf/ambassadors/pull/68.

**Comment by OrlinVasilev** [comment]
@idvoretskyi  - requested access so I can add my location
