### ISSUE TITLE
Free CKA Exam for All Ambassadors

### ISSUE THREAD

**Issue by caniszczyk** [cncf/ambassadors#13]
In 2018, I'd like to waive the fee for all ambassadors taking the CKA Exam.

**Comment by rosskukulinski** [comment]
@caniszczyk As someone who's already passed the exam, I think this would be a nice benefit for our ambassadors.

**Comment by idvoretskyi** [comment]
Fixed https://github.com/cncf/ambassadors/commit/12c0e90ffa078aed07c80513ca6d645f36b10dc2
