### ISSUE TITLE
Meeting notes for December

### ISSUE THREAD

**Issue by rosskukulinski** [cncf/ambassadors#16]
We have been publishing the meeting slides [here](https://github.com/cncf/ambassadors/blob/master/meetings/minutes.md) but it's currently missing the slides from our December meeting.

**Comment by idvoretskyi** [comment]
@rosskukulinski thanks for the heads up, will add them.

**Comment by idvoretskyi** [comment]
Fixed https://github.com/cncf/ambassadors/commit/862b573ea5cb46b11cdeb91e112123c0d894aa72
