### ISSUE TITLE
Come up with Campus Ambassador Toolkit for Students

### ISSUE THREAD

**Issue by caniszczyk** [cncf/ambassadors#21]

**Comment by caniszczyk** [comment]
Chris Short, Bob Killen and Justin Garrison have volunteered to help here

**Comment by luxas** [comment]
And @luxas :wink:

**Comment by idvoretskyi** [comment]
cc @kbarnard10

**Comment by caniszczyk** [comment]
some prior art: https://blog.docker.com/2017/05/announcing-docker-student-developer-kit-campus-ambassador-program/

I have many ideas on how we can do something better.

**Comment by CloudGrimm** [comment]
Is this still being championed or its been shelved?

**Comment by idvoretskyi** [comment]
cc @amye

**Comment by leecalcote** [comment]
I'm interested here. I'm partnered with two universities currently - UT Austin and UEM Jaipur.

**Comment by mrbobbytables** [comment]
+1 here as well.

**Comment by amye** [comment]
Stepping in here to think this through.
I've reviewed the Docker work, and the most compelling part is the Student Ambassador program (which doesn't seem to be currently active.) 
Other Prior Art which seems to be more active: 
https://fedoraproject.org/wiki/Fedora_Student_Mentor_Program#The_Fedora_Student_Mentor_Programme 

Goals: 
* A way to encourage students to get involved with Cloud Native 
* Promotion through student-led workshops + talks
* Mentorship connections with existing ambassadors 

Needs: 
* Mentors
* A signup process
* A quick reworking of existing material to align with student needs + desires
* Stickers 

Fedora has Flock this week so I'm not likely to be able to raise any of that group for a quick 'how we did it', but I'll put that in my inbox for the week of the 12th. 

What else am I missing for a quick MVP program for student ambassadors?

**Comment by CloudGrimm** [comment]
As a current MSc student trying to attract more participants in the Cloud Native journey, I think this is a good starting point. I am not a CNA but have been trying to spread the cloud native technologies to all my peers and the interest is huge. 

When can the MVP framework be rolled out? @amye

**Comment by amye** [comment]
@CloudGrimm: Likely the next two weeks if the pieces align!

**Comment by mrbobbytables** [comment]
Another possible idea/reference point - The [XSEDE Campus Champion Program](https://www.xsede.org/web/site/community-engagement/campus-champions). It includes faculty and such, but they do have a student focused group mostly with the same intentions of the general program.

**Comment by ananthulasrikar** [comment]
I was part of Mozilla Reps in the past. Sharing my 2cents here: https://wiki.mozilla.org/Reps , I am happy to discuss/plan/ share my experiences.

**Comment by 2pai** [comment]
is there any update on this topic ? i'm interested 😄

**Comment by idvoretskyi** [comment]
@2pai this is in a pending state at the moment, but we are open for proposals.

**Comment by sergioarmgpl** [comment]
Well, right now in my Operating System course, i am trying to modify my syllabus to introduce my student to the Cloud Native World. I think that i can share a draft of Syllabus to design something of value for future Cloud Native Students

**Comment by sergioarmgpl** [comment]
I created this repo https://github.com/sergioarmgpl/operating-systems-usac-course with the idea to open my content for my course of operating systems, the idea is to bring resources to introduce the students to a cloud native technologies, there you can find a syllabus and ideas for projects that uses technologies of CNCF projects :) contributions are welcome, we can help cncf projects to test new features in our laboratory :)

**Comment by pasimoes** [comment]
Hello, this initiative is active or died? I have a deep interest in it.

**Comment by amye** [comment]
We can certainly review proposals if you have something, @pasimoes.

**Comment by sergioarmgpl** [comment]
I took the time to edit the Fedora Mentor Programme and adapt it to CNCF. I think that i could work this with Lee Calcote, and the people with Linkerd initially, i am currently trying to create something like this with my students. I currently have some repos to introduce the students to containerd, linkerd, docker, and we are currently working in some open projects in the classroom to test cloud native technologies. I can donate all my repos for this purpose. This is one of my repos: https://github.com/sergioarmgpl/operating-systems-usac-course

Could be great if you can create a slack channel in CNCF slack, to include all this people here, i think that we can build this student movement. I am currently in the CNCF Slack as Sergio Méndez
  
**Campus Ambassador Toolkit for Students**
Campus Ambassador Toolkit is a toolkit to get involved seniors students into the CNCF ecosystem in the way that they can gain experience using cloud native technologies for their future jobs, to develop new contributors and a way to get involved universities to contribute across research, thesis or open source contribution, etc. 
  
**Objectives**
Develop skills in the students to contribute to CNCF projects and create a space for students and universities in the CNCF ecosystem.
  
**The Programme**
The College students(primarily engineering students) have the task of working on issues, research or thesis related to a CNCF Project. The CNCF Mentor here plays a vital role in helping the students work on topics of their interest related to these tasks, developing in that way their skills for the industry or to participate in a GSoC.
The universities have assigned a project to do research about a topic related to Cloud Native Technologies in special new software or ideas that currently involve CNCF Projects. CNCF ambassador helps the university or students to lead the research. 
The programme should not be only on coding. Could be speakers or social media contributors in the same way like the CNCF Ambassador Program https://github.com/cncf/ambassadors.
  
**Advantages**
- Helps CNCF in attracting college students to contribute to their projects.
- Helps CNCF in attracting college students to use cloud native technologies.
- Helps CNCF projects to test new features to speed their release and testing times.
- Involve Students in programs like Community Bridge or Google Summer of Code to contribute with CNCF projects.
- Open a space for students to get jobs related to cloud native technologies.
- Create a space for Universities contribution by doing research with their students using CNCF projects.
- Create a space for innovation and new ideas where universities, students and CNCF can get involved.
- Promote diversity and inclusion in the way that universities and students in other countries can contribute.
  
**To be done**
- List CNCF projects that could be interesting in this student kit.
- Define the minimum skills to develop in potential students contributors
- Define the steps to get involved students into participate into GSoC related to CNCF projects
- List professor, universities that can be interested in this program.
- Generate a vault of projects, features of issues that the students/students can be involved in.
- Assigning the students to the respective mentors based on the projects.
- Define deadlines for testing ideas, issues related to GSoC
- Periodic evaluation of students on the progress of the projects by the mentors.
- A Certificate and a small token of appreciation on successful completion of the project.
- Ambassadors to publicise the mentors programme and help students with a smooth entry in the project.
- If possible create a CNCF conference for students to promote students participation
- Gather students opinions about this kind of opportunities to enrich this student kit
- Work together with universities to update their syllabus in the way to include cloud native theory in their courses.
- Provide courses or small guides to create a quickstart to contribute to CNCF projects.
  
**Conducting CNCF Webinars and conferences in Colleges**
As part of the mentor programme, conducting CNCF webinars and conferences in college helps CNCF in attracting more students and there-by increasing the user base and also creating an awareness of what CNCF projects are and its benefits.
**Advantages**
- Generate Ideas and Innovation related to cloud native technologies in specific CNCF projects
- Create a sustainable way to test, innovate and contribute together with the industry and the academy
- Increase in developer/contributor base for CNCF projects.
- A ambassador program recognition for students for their efforts
- More Academic contacts covering more areas.
- Promote CNCF in the academic field. 
  
**Issues to be resolved**
Pending please list this issues here

**Comment by idvoretskyi** [comment]
@sergioarmgpl this is great, thank you!

**Comment by sergioarmgpl** [comment]
@idvoretskyi @amye let me know how i can help.

**Comment by amye** [comment]
It seems like the first step here is getting a slack channel and that's easy to kick off.
Come find me on Slack and I'll make you a channel.

**Comment by xmulligan** [comment]
@sergioarmgpl do you have time to discuss your syllabus a bit further? I would love to get some of your ideas on this https://calendly.com/billmulligan/1-1-with-bill-mulligan

**Comment by xmulligan** [comment]
@mrbobbytables @rothgar @luxas @leecalcote @CloudGrimm @ananthulasrikar @2pai @pasimoes if you have any ideas you would like to share on this I would also love to chat with you. Just book a time that works for you https://calendly.com/billmulligan/1-1-with-bill-mulligan

**Comment by sergioarmgpl** [comment]
i already had a call with @xmulligan, it was a nice time to share ideas :)

**Comment by ananthulasrikar** [comment]
> It seems like the first step here is getting a slack channel and that's easy to kick off.
> Come find me on Slack and I'll make you a channel.

@amye May I please know what is the name of the channel (if created)?

**Comment by amye** [comment]
You'll find this under the CNCF slack, it's the #students channel

**Comment by xmulligan** [comment]
Moving the discussion to https://github.com/cncf/mentoring/issues/314 as it doesn't fit exactly under the Ambassadors Program

**Comment by xmulligan** [comment]
This is currently being worked on in https://github.com/cncf/students. Please contact me if you want to help work on this before it is public
