### ISSUE TITLE
Add Sticker Packages for Ambassadors to the Store

### ISSUE THREAD

**Issue by jberkus** [cncf/ambassadors#22]
Currently the CNCF store is set up to sell individual stickers, not packs.  This means that an Ambassador who needs, say, 400 assorted stickers for an event is going to be out-of-pocket for $200 until they're reimbursed, which is annoying for some of us and prohibitive for Campus Ambassadors.  It's also probably fairly inefficient on the fulfillment side.

I propose instead that the CNCF create a set of "sticker packs" containing different packs of stickers in event quatities, and that the ambassadors be given a code which zeros out the charge for these packs.  My suggestions, based on my own giveaways:

* 100 of any specific project
* Mixed sticker pack: 100x kubernetes 25x of each other project

**Comment by idvoretskyi** [comment]
@jberkus thanks, we will work on this.

**Comment by idvoretskyi** [comment]
Fixed with https://store.cncf.io/collections/ambassador-packs.
