### ISSUE TITLE
Links for KubeWeekly 154

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/ambassadors#38]
**Tools:**
* [Dive](https://github.com/wagoodman/dive) - A tool for exploring a container image, layer contents, and discovering ways to shrink your image size.

* [OpenUnison Kubernetes Active Directory Authentication Provider](https://github.com/OpenUnison/openunison-k8s-login-activedirectory) - An AD authentication provider from TremoloSecurity.

**Articles:**
* [Container Networking Interface aka CNI](https://medium.com/@vikram.fugro/container-networking-interface-aka-cni-bdfe23f865cf) - Introduction to the Container Networking Interface 

* [Why and how do we run Kubernetes on the Spot instances](https://medium.com/preply-engineering/why-and-how-do-we-run-kubernetes-on-the-spot-instances-c88d32fb9df3) - Article from the Preply engineering team on running their  Dev and QA environments on top AWS Spot Instances (with significant savings).

* [Effectively Managing Kubernetes Resources with Cost Monitoring](https://medium.com/kubecost/effectively-managing-kubernetes-with-cost-monitoring-96b54464e419) - Overview of cost monitoring practices and some very useful Grafana Charts.

**Presentations:**

* [Signing Helm Charts & Helm v3 with Matt Farina](https://www.slideshare.net/mattfarina/helm-orchestructure) ([video](https://www.youtube.com/watch?v=SQC_yuVAAhM)) - Presentation from the [October CNCF Orchestructure meetup in Ann Arbor, MI](https://www.meetup.com/orchestructure/events/255439094/). Matt Farina  a Helm Maintainer and co-chair of sig-apps explores some advanced and often overlooked Helm techniques; along with going over whats in store for Helm v3.

**Comment by caniszczyk** [comment]
Add link to Envoy Proxy starting their QUIC support:
https://twitter.com/mattklein123/status/1057411886348562432

**Comment by caniszczyk** [comment]
OPA had a new v0.10 release (https://blog.openpolicyagent.org/v0-10-release-277da41b9ed1) +  roadmap was published: https://docs.google.com/presentation/d/11_OBKbx8qK8bx35n3jRtluLnIBXgZwNpcJdEEGDd6YQ/edit
