### ISSUE TITLE
Links for KubeWeekly #157

### ISSUE THREAD

**Issue by chris-short** [cncf/ambassadors#42]
Links due by 11am PT on Wednesday November 28th.

**Comment by chris-short** [comment]
Here is everything I think is worth sharing is this week. I think it'd be best if @kbarnard10 organizes them as categorizing things is hard enough but, wait until there's a conflict (editorial vs. technical, etc.).

* [danderson/virtuakube](https://github.com/danderson/virtuakube) — Virtuakube sets up virtual Kubernetes clusters for testing.

* [Benchmark results of Kubernetes network plugins (CNI) over 10Gbit/s network](https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-36475925a560) — An eye-opening CNI benchmark report. YMMV.

* [K8s Selenium Grid — Selenium Grid with Docker on Kubernetes](https://medium.com/@subbarao.pilla/k8s-selenium-grid-selenium-grid-with-docker-on-kubernetes-42af8b9a2cba) — Use minikube to spin up and run Selenium Grid on your laptop. I've needed this since 2012. Thank you, Kubernetes.

* [Kubernetes Ingress Controllers and Certificates: The Walkthrough](https://jessicadeen.com/kubernetes-ingress-controllers-and-certificates-the-walkthrough/) — Jessica Deen’s video walkthrough of Ingresses and Helm Charts

**Comment by surajnarwade** [comment]
not sure if this is good fit for kubeweekly:

* https://suraj.pro/post/journey-to-cka/
