### ISSUE TITLE
Affiliation update

### ISSUE THREAD

**Issue by castrojo** [cncf/ambassadors#47]
https://www.cncf.io/people/ambassadors/

Heptio->VMware affiliations need to be updated for Jorge Castro, Kris Nova, and Ross Kukulinksi.

**Comment by caniszczyk** [comment]
cc: @kbarnard10

**Comment by kbarnard10** [comment]
Updated

**Comment by castrojo** [comment]
@kbarnard10 The descriptions still mention Heptio. :D

**Comment by kbarnard10** [comment]
Ok I think I caught them all this time.
