### ISSUE TITLE
KubeWeekly #163

### ISSUE THREAD

**Issue by gianarb** [cncf/ambassadors#49]
Please respond to this issue with links for the next edition of KubeWeekly. Links are due by 11am PT every Wednesday. @kbarnard10 will combine the links into the final email and send out. 

**Featured Content**
_Editor's picks of the highlights from the past week._
[ARTICLE TITLE](LINK)

**Technical** 
_Tutorials, tools, and more that take you on a deep dive into the code._
[Extend Kubernetes via a Shared Informer](https://gianarb.it/blog/kubernetes-shared-informer)

_Tooling:_
[Cilium 1.4: Multi-Cluster Service Routing, DNS Authorization, IPVLAN support, Transparent Encryption, Flannel Integration, Benchmarking other CNIs, ...](https://cilium.io/blog/2019/02/12/cilium-14)

**The Editorial** 
_Articles, announcements, and more that give you a high-level overview of challenges and features._
[ARTICLE TITLE](LINK)

**GUIDELINES**
- Articles must be published within the last ~1 week. 
- No gated content, unless in the webinar section. 
- Blog posts and videos are the preferred medium.

**Comment by mhausenblas** [comment]
* https://www.infoq.com/podcasts/joe-beda-kubernetes-cncf
* https://itnext.io/pimp-my-kubernetes-shell-f144710232a0

**Comment by mrbobbytables** [comment]
**Editorials:**
- [Kubernetes Storage Performance Comparison](https://medium.com/vescloud/kubernetes-storage-performance-comparison-9e993cb27271)

Not a lot this week. :x
