### ISSUE TITLE
KubeWeekly #165 - March 20th

### ISSUE THREAD

**Issue by kbarnard10** [cncf/ambassadors#51]
Please respond to this issue with links for the next edition of KubeWeekly. Links are due by 11am PT every Wednesday. @kbarnard10 will combine the links into the final email and send out. 

**Featured Content**
_Editor's picks of the highlights from the past week._
[ARTICLE TITLE](LINK)

**Technical** 
_Tutorials, tools, and more that take you on a deep dive into the code._
[ARTICLE TITLE](LINK)

_Tooling:_
[ARTICLE TITLE](LINK) - one sentence description

**The Editorial** 
_Articles, announcements, and more that give you a high-level overview of challenges and features._
[ARTICLE TITLE](LINK)

**GUIDELINES**
- Articles must be published within the last ~1 week. 
- No gated content, unless in the webinar section. 
- Blog posts and videos are the preferred medium.

**Comment by mrbobbytables** [comment]
**Technical:**
- [Running Kubernetes In The CI Pipeline For Integration and End-To-End Tests](https://www.loodse.com/blog/2019-03-12-running-kubernetes-in-the-ci-pipeline-/)
- [Running a Tight Ship: Deploying Kubernetes to Run Windows Containers](https://medium.com/outsystems-engineering/running-a-tight-ship-deploying-kubernetes-on-a-windows-server-429c9b4e6c3e)

**Editorial:**
- [How A Cryptocurrency Miner Made Its Way onto Our Internal Kubernetes Clusters](https://medium.com/jw-player-engineering/how-a-cryptocurrency-miner-made-its-way-onto-our-internal-kubernetes-clusters-9b09c4704205)
- [Routing in a Multi-Platform Data Center: From VMs to Kubernetes, via Ambassador](https://blog.getambassador.io/routing-in-a-multi-platform-data-center-from-vms-to-kubernetes-via-ambassador-47bbe658683c)

**Comment by chris-short** [comment]
[Creating a Kubernetes Cluster with Digital Ocean and Terraform](https://ponderosa.io/blog/kubernetes/2019/03/13/terraform-cluster-create/) — Using Terraform to build a Kubernetes cluster on Digital Ocean

[Kubernetes Patterns](http://shop.oreilly.com/product/0636920242598.do) — "Each pattern includes a description of the problem and a proposed solution with Kubernetes specifics. Many patterns are also backed by concrete code examples. This book is ideal for developers already familiar with basic Kubernetes concepts who want to learn common cloud native patterns."

[The What and the Why of the Cluster API](https://blogs.vmware.com/cloudnative/2019/03/14/what-and-why-of-cluster-api/) — "In this post, we will outline the history and motivations behind the creation of the Cluster API as a specialized toolset to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management in the Kubernetes ecosystem."

[gRPC Load Balancing inside Kubernetes](https://blog.nobugware.com/post/2019/kubernetes_mesh_network_load_balancing_grpc_services/) — "Load-balancing proxies are great tools, especially useful on the edge of your platform. “Mesh Network” solutions are nice additions to our tool set, but the cost of operating and debugging a full mesh network could be really expensive and overkill in some situations, while a client load balancing solution is simple and easy to grasp."

[Kubernetes Setup Using Ansible and Vagrant](https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/) — "This blog post describes the steps required to setup a multi node Kubernetes cluster for development purposes. This setup provides a production-like cluster that can be setup on your local machine."

[Kubernetes - The Fast and Furious?](https://www.weave.works/blog/kubernetes-the-fast-and-furious) — "Alexis Richardson recently spoke at the two day event Container Stack in Zurich and described the role of the CNCF and what it means to be cloud native. After a brief introduction on the CNCF and its role, Alexis then explained the type of projects and how they get accepted to the foundation before diving into how enterprises can benefit by adopting cloud native technology."

[How to deploy NuoDB on Kubernetes with OpenEBS](https://blog.openebs.io/how-to-deploy-nuodb-on-kubernetes-with-openebs-6e15d4064db5) — "NuoDB is a container-native adaptive-scale distributed SQL database designed with distributed application deployment challenges in mind."
