### ISSUE TITLE
Plan to make CNCF ambassadors bigger :-)

### ISSUE THREAD

**Issue by ananthulasrikar** [cncf/ambassadors#6]
Hi Chris,

I wud like you to check abt Mozilla reps program ( https://reps.mozilla.org , https://wiki.mozilla.org/ReMo), we were part of core team in its nascent stages and it's pretty huge now. I have been part of reps program for abt 4 years. I feel this kind of program wud be a great help to build more CNCF awareness and especially can focus on students to get them started.

**Comment by idvoretskyi** [comment]
@ananthulasrikar actually what I've been looking for already :)

Thanks for sharing, we will review it deeper.

cc @caniszczyk

**Comment by ananthulasrikar** [comment]
That's great to hear. Let me know how I can help :) I am happy to take this forward.

**Comment by idvoretskyi** [comment]
@ananthulasrikar based on your experience of participating in both programs, can you highlight the most notable enhancements from Mozilla reps program, that may positively influence our program?

Thanks

**Comment by caniszczyk** [comment]
closing as this isn't a concrete action item we can perform, let's try to break apart any ideas from the mozilla program into concrete issues that we can work on :)
