### ISSUE TITLE
Annual Ambassador Mixed Decal Pack as a Benefit

### ISSUE THREAD

**Issue by caniszczyk** [cncf/ambassadors#60]

**Comment by caniszczyk** [comment]
idea via Archy

**Comment by InAnimaTe** [comment]
I think this as well as some other swag/gear items would be great. Everyone gets bombarded with stickers so maybe coasters, mugs, or other things a couple times a year or once per quarter would be awesome.

**Comment by qedrakmar** [comment]
How about an option for decal packs?  I have a box full of most projects' decals, but run out of any kubernetes stickers I have at every meetup, and it may not be the same for every region.

**Comment by caniszczyk** [comment]
@qedrakmar I can update to the wording of a decal pack of your of choice

**Comment by caniszczyk** [comment]
Note: you can always request things as a case by case basis
