### ISSUE TITLE
Emeritus me

### ISSUE THREAD

**Issue by rothgar** [cncf/ambassadors#70]
I'd like to opt in to become an emeritus CNCF ambassador.

Please let me know if there is anything you need from me to change my active ambassador status.

**Comment by idvoretskyi** [comment]
Thank you for all your active service, @rothgar!

cc @amye @caniszczyk

**Comment by rothgar** [comment]
I have a [meetup](https://www.meetup.com/ieatca) (which I never really did much with) that was part of the CNCF. I don't remember if funding for those required active ambassador status or not.

If my ambassador status means this would lose CNCF funding I can close the group, but I would appreciate guidance here

**Comment by luxas** [comment]
ping @idvoretskyi @caniszczyk 
@rothgar see example PR at https://github.com/cncf/ambassadors/pull/71
