### ISSUE TITLE
Please add me to CNCF Ambassador Map

### ISSUE THREAD

**Issue by karenhchu** [cncf/ambassadors#73]
Hi there, 

I am missing from this list -- https://www.google.com/maps/d/u/0/viewer?mid=1fb0UPi8ijeexueBxcpGuvVlZ_8hJHXVQ&ll=37.774929500000034%2C-122.41941550000001&z=12

You can put me down for San Francisco or Boulder (I am the host of the Kubernetes Colorado meet-up). 

Thank you!

**Comment by idvoretskyi** [comment]
@karenhchu done, thanks for pointing out!
