### ISSUE TITLE
Please help to add me  to CNCF Ambassador Map

### ISSUE THREAD

**Issue by Vivian7755** [cncf/ambassadors#75]
Hi , 
Cannot find me on the ambassor map : https://www.google.com/maps/d/u/0/viewer?mid=1fb0UPi8ijeexueBxcpGuvVlZ_8hJHXVQ&ll=37.74703801476318%2C-122.21965849881485&z=10

You can set me at Beijing or Mountain View (travels there office sometimes ). 

Thanks you  :)

**Comment by idvoretskyi** [comment]
@Vivian7755 we prefer tagging the ambassadors on the map with the single place of permanent/preferred residence, is it Beijiing or Mountain View? :)

**Comment by Vivian7755** [comment]
@idvoretskyi ， Beijing please :）

**Comment by idvoretskyi** [comment]
@Vivian7755 done!
