### ISSUE TITLE
Content proposal for KubeWeekly editorial

### ISSUE THREAD

**Issue by carlisia** [cncf/ambassadors#79]
**The Editorial** 
_Articles, announcements, and more that give you a high-level overview of challenges and features._
[Kubernetes as per Kelsey Hightower - YouTube](https://www.youtube.com/watch?v=yYzIOx0Bbg0)

[Bonus Episode: Kelsey Hightower on Kubernetes - podcast](https://ifelsepodcast.com/episodes/bonus-episode-kelsey-hightower-on-kubernetes)

**Comment by idvoretskyi** [comment]
@carlisia where these links should be published?

**Comment by carlisia** [comment]
Hi @idvoretskyi, this is my first submission so I might not be well-versed on where things should go. I thought the "editorial" section was the right section.

**Comment by idvoretskyi** [comment]
cc @KimMcMahon

**Comment by idvoretskyi** [comment]
This should be fixed now :)
