### ISSUE TITLE
CNCF Copyright is 2019

### ISSUE THREAD

**Issue by onlydole** [cncf/ambassadors#83]
Hello team! I found a minor not, and it looks like the cncf.io site still has 2019 for the copyright year.

**Comment by onlydole** [comment]
![image](https://user-images.githubusercontent.com/117500/72743853-4b55c480-3b61-11ea-89b4-80b76a1ae844.jpg)

**Comment by idvoretskyi** [comment]
cc @dankohn

**Comment by onlydole** [comment]
This has been fixed!
