### ISSUE TITLE
Ambassador architecture icons Libraries

### ISSUE THREAD

**Issue by ipyker** [cncf/ambassadors#97]
![image](https://user-images.githubusercontent.com/48749744/128634643-67d821ae-a90e-4780-b08b-be4accf58bd2.png)
This architecture icon is so cool, is there an xml file for draw.io?

**Comment by idvoretskyi** [comment]
@ipyker I believe you meant the Ambassador/Emissa project - https://github.com/emissary-ingress/community, which is a different thing from the CNCF Ambassador program, so please open an issue there.
